### ISSUE TITLE
need to update the plugin

### ISSUE THREAD

**Issue by maoaixianyu** [square/otto-intellij-plugin#24]
when i clicks the logo, it  alert the popup.  Otto Plugin threw an uncaught NoClassDefFoundError. It needs to change the plugin configuration. How can i do?  My AS is 2.2 Preview 6. Thanks.

**Comment by yankeppey** [comment]
The same error for stable version of AS 2.2.
Otto bus project is deprecated, so probably we should expect square developers to fix it soon.

**Comment by m4fi3ux** [comment]
You can get 2.2 plugin from my fork : https://github.com/m4fi3ux/otto-intellij-plugin/blob/master/otto-intellij-plugin.jar

**Comment by sezn** [comment]
Top! thanks, it works with AS 2.2!

**Comment by SuperKung** [comment]
@m4fi3ux Thx ！It's work!!

**Comment by pranaysharma** [comment]
@m4fi3ux works thanks a ton

**Comment by TomWangTW** [comment]
Here is for AS 4.x:https://github.com/TomWangTW/otto-intellij-plugin/blob/master/otto-intellij-plugin-forandroid4.x.jar
